spring:
  application:
    name: spring-cloud-zuul

server:
  port: 8201

zuul:
  routes:
    sso:
     path: /sso/**
     serviceId: wangluo-service-sso
    gis:
     path: /gis/**
     serviceId: wangluo-api-gis
    test:
     path: /test/**
     url: http://192.168.0.2:8531/

