spring:
  application:
    name: spring-cloud-eureka

server:
  port: 8101



eureka:
  instance:
    hostname: 192.168.0.3
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

