spring:
  application:
    name: spring-cloud-zuul

server:
  port: 8201


hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 60000
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

zuul:
  max:
    host:
      connections: 60000
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
  ignoredServices: '*' #忽略所有未配置的service
  routes:
    index:
      path: /**
      serviceId: wangluo-service-admin
      sensitiveHeaders: "*"
    sso:
      path: /sso/**
      serviceId: wangluo-service-admin
      sensitiveHeaders: "*"
    gis:
      path: /gis/**
      serviceId: wangluo-service-gis
      sensitiveHeaders: "*"

    site:
      path: /site/**
      serviceId: wangluo-service-site
      sensitiveHeaders: "*"