spring:
  application:
    name: spring-cloud-zuul

server:
  port: 8201

zuul:
  host:
    socket-timeout-millis: 10000
    connect-timeout-millis: 2000
  ignoredServices: '*' #忽略所有未配置的service
  routes:
    sso:
      path: /sso/**
      #url: http://192.168.0.2:8531/
      serviceId: wangluo-service-sso
      sensitiveHeaders: "*"
    gis:
      path: /gis/**
      serviceId: wangluo-service-gis
      sensitiveHeaders: "*"

